
use_frameworks!
platform:ios, '12.0'
inhibit_all_warnings!

target 'Frameworks_Swift_Example' do
  
  pod 'Frameworks_Swift', :path => '../'

  target 'Frameworks_Swift_Tests' do
    inherit! :search_paths
  end
  
end
